baseURL = "https://www.drossel.studio/"
languageCode = "ja-jp"
title = "Drossel Studio"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 2
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 3
[[menu.main]]
name    = "Activity"
url     = "activity"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5

# Site Params
[params]
home = "Home"
logo = "images/DS/DSlogo_small.png"
dateFormat = "6 January 2006"
# Meta data
description = "Drossel/Studioはゲームを中心に様々なデジタルコンテンツを開発するサークルです。"
author = "Drossel/Studio"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/header.png"
heading = ""
description = ""
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
#[[params.banner.flipText]]
#title   = "DESIGNER"
#[[params.banner.flipText]]
#title   = "DEVELOPER"
#[[params.banner.flipText]]
#title   = "FATHER"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT"
content = "Drossel/Studioはゲームを中心に様々なデジタルコンテンツを開発するサークルです。"
image   = "images/DS/DSlogo2.png"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Works"
subtitle= ""

# social icon
# [[params.socialIcon]]
# icon = "ion-social-facebook"
# url = "#"

# [[params.socialIcon]]
# icon = "ion-social-instagram"
# url = "#"

# [[params.socialIcon]]
# icon = "ion-social-linkedin"
# url = "#"

# HTMLタグ埋め込みの有効化
[markup.goldmark.renderer]
unsafe= true

